1. Выполнить установку и подключение библиотеки в программе на языке Python. Для этого рекомендуется использовать менеджер пакетов pip.

In [1]:
!pip install numpy
import numpy as np
import random

2. Выполнить генерацию:

a. линейного массива (вектора) чисел с плавающей точкой произвольного размера; 



c. генерацию массивов выполнять с размерностью в сотни, тысячи, сотни тысяч
элементов.


d. для каждого массива выполнить оценку времени, затраченного на генерацию. e. сравнить показатели с массивами, генерируемыми средствами стандартной библиотеки языка Python аналогичной размерности.

In [2]:
def lin_array_numpy(n,x=0,y=100):
    """Создание линейного массива в библиотеке numpy"""
    lin_arr=np.linspace(x, y, n)
    random.shuffle(lin_arr)
    %time
    print()
    print(lin_arr)    

In [3]:
def lin_array_python(n):
    """Создание линейного массива в стандартном питоне"""
    list_=[]
    lin_array_python=[random.uniform(0,100) for i in range(n)]
    k = %time
    print()
    print(lin_array_python) 

In [33]:
# сотни
lin_array_python(200)

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 11.9 µs

[44.04690403705119, 16.181433890217168, 86.86887149611904, 91.28289052066813, 30.024441227165866, 21.78160428794057, 45.74217368521107, 70.75738771636944, 65.2103923325606, 46.868377855200116, 37.870164423728255, 18.569354649124236, 61.88633641849025, 85.77804055879221, 59.830227986823004, 22.490474009644334, 71.64605134686059, 74.28308842594677, 34.46318409638205, 44.938762385915474, 22.07344757750782, 3.199737098845812, 10.514271771295325, 4.148166617645776, 79.71309661934086, 43.62261928327451, 35.266281732248736, 71.74155061996606, 66.45613149995336, 17.279620466634917, 34.708391160056294, 21.437937499127514, 46.451512937346465, 26.031158912495666, 86.37092595700692, 70.32737938129895, 82.4931918083279, 5.102032718017591, 36.93835029149767, 28.317135304105467, 6.120900930992834, 43.588844848406104, 4.1242415344946775, 56.40090393249405, 58.87905419577285, 86.24913719773865, 25.54175108147484, 37.54149181450895, 23.278

In [34]:
# сотни
lin_array_numpy(200)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 7.87 µs

[ 51.25628141  94.97487437  85.42713568  89.94974874  96.98492462
  19.09547739  85.92964824  88.44221106  42.71356784  29.14572864
  15.57788945  78.89447236  64.32160804  62.31155779  73.36683417
  93.96984925  37.18592965  64.8241206   92.46231156  14.57286432
  95.9798995   67.33668342  82.91457286  17.08542714  84.42211055
  78.3919598   63.31658291  95.47738693  80.40201005  34.17085427
  36.68341709  40.20100503  16.08040201  20.60301508  32.16080402
  48.74371859  96.48241206  41.70854271  26.63316583  92.96482412
  61.30653266   9.54773869 100.          10.55276382  83.91959799
  46.73366834  99.49748744  53.76884422   9.04522613  57.28643216
  48.24120603   3.01507538  65.82914573  12.56281407  31.15577889
   0.50251256  13.06532663  36.18090452  15.07537688  62.81407035
  84.92462312  77.38693467  31.65829146  71.35678392  35.1758794
  58.29145729  87.43718593  71.85929648  89.44723618  28.14070352
  37.6884422

In [29]:
# тысячи
lin_array_python(2000)


CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.91 µs

[5.149222821549548, 55.23549400339986, 37.95216813314598, 5.13821819243171, 6.752984470537127, 43.59122354954368, 0.25933091277376974, 35.88061709329038, 66.7151443935254, 79.58072966440054, 57.751171981989245, 15.334450146967916, 27.22868593624129, 27.264716944773614, 16.12648035230603, 69.70683615679071, 48.391689029097684, 65.5374128077126, 31.377034808891334, 21.220184698821797, 44.17538979540234, 11.211731309622873, 96.51518720959189, 35.36247828676811, 49.43140665664168, 20.885074528987747, 31.643037357342052, 49.678153586741125, 2.6281473545638034, 10.64159740283549, 94.13334975953686, 19.24782225359073, 54.41425462960178, 38.15360091355928, 27.656320702941784, 56.49001473361944, 11.827644523545821, 79.30855928003344, 79.3906765172103, 61.60163077722074, 55.04204044776808, 41.520214633611786, 44.0024356876708, 88.55131309681138, 25.44443326363962, 11.723350580318115, 17.938853724219804, 30.126254683982733, 23.62906

In [30]:
# тысячи
lin_array_numpy(2000)

CPU times: user 4 µs, sys: 2 µs, total: 6 µs
Wall time: 12.2 µs

[48.57428714 53.92696348 81.24062031 ... 93.64682341 48.12406203
 15.45772886]


In [31]:
# сотни тысяч
lin_array_python(100_000)

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 5.96 µs

[99.25579919774802, 51.91122188965823, 84.52480036653313, 80.06391091025384, 55.986167402917744, 38.959470674631646, 52.88008722507646, 98.9234261222772, 34.981104952119544, 22.759082413643572, 17.574587633145967, 85.3107947560524, 49.78943795455518, 32.40399521131271, 45.02992756653062, 21.40834765091917, 32.0493468701356, 94.56750750932818, 66.51281323780273, 84.44691557614826, 75.24816111745484, 71.89244149565162, 21.185656426583233, 87.16311588192751, 51.819317798209795, 61.14942563483554, 36.99986524856119, 83.60910937561759, 18.35173693836707, 96.67880303656825, 89.80013619776469, 47.208982395812015, 88.19565514326779, 6.997001956380389, 1.6199470290239493, 92.5110969495903, 77.942220293425, 98.91716395329085, 45.21803272198039, 97.450925671698, 37.39164646567224, 84.62131738229569, 24.06338831471666, 10.369597537385388, 32.10025502852971, 80.13811028210743, 6.723013246629106, 50.966402431156155, 42.474444599627

In [32]:
# сотни тысяч
lin_array_numpy(100_000)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.2 µs

[38.63738637 14.52814528 26.0102601  ... 64.6796468   4.11604116
 88.06888069]


### генерация массивов с помощью библиотеки стандартные библиотеки питона происходит быстрее, чем генерация массивов через numpy 

b. выполнить генерацию двумерного массива (матрицы) чисел с плавающей точкой
произвольного размера;

In [10]:
matrix1=np.asfarray(np.arange(1, 51,2)).reshape(5, 5)
matrix1

array([[ 1.,  3.,  5.,  7.,  9.],
       [11., 13., 15., 17., 19.],
       [21., 23., 25., 27., 29.],
       [31., 33., 35., 37., 39.],
       [41., 43., 45., 47., 49.]])

In [11]:
matrix2=np.asfarray(np.arange(50, 100,2)).reshape(5, 5)
random.shuffle(matrix2)

matrix2

array([[50., 52., 54., 56., 58.],
       [60., 62., 64., 66., 68.],
       [60., 62., 64., 66., 68.],
       [50., 52., 54., 56., 58.],
       [70., 72., 74., 76., 78.]])

3. Выполнить все арифметические операции над элементами двумерного массива.


In [12]:
# поэлементное сложение
print(matrix1+matrix2)

[[ 51.  55.  59.  63.  67.]
 [ 71.  75.  79.  83.  87.]
 [ 81.  85.  89.  93.  97.]
 [ 81.  85.  89.  93.  97.]
 [111. 115. 119. 123. 127.]]


In [13]:
print(matrix2+10)

[[60. 62. 64. 66. 68.]
 [70. 72. 74. 76. 78.]
 [70. 72. 74. 76. 78.]
 [60. 62. 64. 66. 68.]
 [80. 82. 84. 86. 88.]]


In [14]:
# поэлементное вычитание
print(matrix2-matrix1)

[[49. 49. 49. 49. 49.]
 [49. 49. 49. 49. 49.]
 [39. 39. 39. 39. 39.]
 [19. 19. 19. 19. 19.]
 [29. 29. 29. 29. 29.]]


In [15]:
# поэлементное умножение
print(matrix1*matrix2)

[[  50.  156.  270.  392.  522.]
 [ 660.  806.  960. 1122. 1292.]
 [1260. 1426. 1600. 1782. 1972.]
 [1550. 1716. 1890. 2072. 2262.]
 [2870. 3096. 3330. 3572. 3822.]]


In [16]:
# поэлементное деление
print(matrix2/matrix1)

[[50.         17.33333333 10.8         8.          6.44444444]
 [ 5.45454545  4.76923077  4.26666667  3.88235294  3.57894737]
 [ 2.85714286  2.69565217  2.56        2.44444444  2.34482759]
 [ 1.61290323  1.57575758  1.54285714  1.51351351  1.48717949]
 [ 1.70731707  1.6744186   1.64444444  1.61702128  1.59183673]]


In [17]:
print(matrix2/10)

[[5.  5.2 5.4 5.6 5.8]
 [6.  6.2 6.4 6.6 6.8]
 [6.  6.2 6.4 6.6 6.8]
 [5.  5.2 5.4 5.6 5.8]
 [7.  7.2 7.4 7.6 7.8]]


4. В качестве полноценного упражнения реализовать игру «Жизнь» использованием NumPy.


In [39]:
import time

In [40]:
def neighbor_xy(x, y):
    for dx, dy in {
        (0, 1),
        (1, 1),
        (1, 0),
        (1, -1),
        (0, -1),
        (-1, -1),
        (-1, 0),
        (-1, 1)
    }:
        yield x + dx, y + dy

def show_field(field):
    for y in range(MAX_SIZE):
        print(f'{field[y]}')
        
def get_empty_field():    
    return np.full((MAX_SIZE, MAX_SIZE), DEAD)
        
def is_live(field, neighbor_x, neighbor_y):
    return 0 <= neighbor_x < MAX_SIZE and 0 <= neighbor_y < MAX_SIZE and field[neighbor_y][neighbor_x] == LIVE

In [41]:
MAX_SIZE = 20
DEAD = 0
LIVE = 1
field = np.random.randint(0,2,(MAX_SIZE,MAX_SIZE))

while True:
    show_field(field)
    buffer = get_empty_field()
    for y in range(MAX_SIZE):
        for x in range(MAX_SIZE):
            c = field[y][x]
            neighbors = 0
            for neighbor_x, neighbor_y in neighbor_xy(x, y):
                neighbors += 1 if is_live(field, neighbor_x, neighbor_y) else 0
                pass
            if c == DEAD:
                buffer[y][x] = LIVE if neighbors == 3 else DEAD
            else:
                buffer[y][x] = LIVE if neighbors == (2, 3) else DEAD
                
    if (field == buffer).all():
        print('stasis')
        break
    field = buffer
    time.sleep(2)
    print('Next: ')

[0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 1 0 1]
[0 1 1 0 1 1 1 0 0 0 1 1 1 1 0 0 1 1 0 1]
[1 0 0 0 0 1 0 0 1 0 1 0 1 1 0 1 0 0 1 1]
[0 1 1 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1]
[1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 0]
[1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 1 0 1 1 0]
[0 0 1 0 0 0 1 0 1 1 1 1 0 0 0 0 1 1 1 1]
[0 0 0 1 1 1 0 0 1 1 0 0 0 1 0 1 1 0 1 0]
[1 0 1 1 1 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0]
[1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0]
[0 0 0 0 0 1 0 1 1 1 0 0 1 1 0 1 0 0 0 0]
[0 1 1 0 0 0 1 1 1 1 0 1 0 1 0 0 0 0 1 0]
[1 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1]
[1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1]
[1 0 0 0 1 0 1 1 1 0 1 1 0 1 0 0 1 0 1 0]
[1 0 0 1 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 0]
[1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 0]
[1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 0 1 1]
[0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0 0 1 1]
[0 1 1 1 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0]
Next: 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 1 1 1 0 0 0 0 0 